apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app-dep
  labels:
    app: dummy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app-busybox
        image: busybox:latest
        command:
        - sleep
        - "99999"
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "10Mi"
            cpu: "110m"