apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/app1/v1

namespace: app1-ns

# https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize
configMapGenerator:
  - name: app1-config-values
    behavior: merge
    files:
      - values.yaml=values-override.yaml
configurations:
  - kustomizeconfig.yaml
