apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: buzzfrog-kust
  namespace: default
spec:
  interval: 30s
  path: ./clusters/cluster1
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-buzzfrog
  targetNamespace: default
  timeout: 1m
  wait: true