apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../apps

helmCharts:
- name: boiler-helm
  releaseName: moonshot-sample-v1
  namespace: moonshot-sample
  valuesFile: values.yaml